source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target "Master" do
pod 'Mantle', '~> 1.4'
pod 'Overcoat', '~> 1.2'
#pod 'SDCycleScrollView'
pod 'RongCloudIMLib'
pod 'DGActivityIndicatorView'
#pod 'ZXingObjC'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'TMCache'
pod 'MBProgressHUD'
pod 'HPGrowingTextView'
pod 'UMengSocial'
pod 'UMengMessage'
pod 'UMengAnalytics-NO-IDFA'
#pod 'SMS-For-iOS', '1.2.0'
pod 'CVKHierarchySearcher'
pod 'CWStatusBarNotification', '~> 2.3.4'
pod 'YYText'
#pod 'YYKit'
#pod 'JPSVolumeButtonHandler', '1.0.0'
#pod 'SBJson', '~> 4.0'
end
